#spring:
#  jpa:
#    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
#    hibernate:
#      ddl-auto: update
#    show-sql: true
#
#  datasource:
#    url: jdbc:mysql://localhost:3306/80000coding?serverTimezone=UTC&characterEncoding=utf8
#    username: sa
#    password:
#    driver-class-name: com.mysql.cj.jdbc.Driver