palco:
  domain:
    backend: ${PALCO_DOMAIN_BACKEND}
---
spring.config.activate.on-profile: local

server:
  port: 8081
spring:
  datasource:
    hikari:
      driver-class-name: com.mysql.cj.jdbc.Driver
      jdbc-url: ${DB_URL}
      username: ${DB_USER_NAME}
      password: ${DB_PASSWORD}
      maximum-pool-size: 5 # (default 10)
      minimum-idle: 5 # (default 10)
      max-lifetime: 1200000 # 20m (default 30m)
      connection-timeout: 3000 # 3s (default 30s)
      validation-timeout: 2000 # 2s (default 5s)
  jpa:
    database: MYSQL
    database-platform: org.hibernate.dialect.MySQL8Dialect
    open-in-view: false
    generate-ddl: false
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true
  data.redis:
    host: localhost
    port: 6379
  security: #OAuth2 연동 어플리케이션 정보 (TODO : 운영 어플리케이션 정보로 수정 필요)
    oauth2:
      client:
        registration:
          github:
            client-id: ${OAUTH2_GITHUB_CLIENT_ID}
            client-secret: ${OAUTH2_GITHUB_CLIENT_SECRET}

logging:
  level:
    com.zaxxer.hikari.HikariConfig: DEBUG
#    com.zaxxer.hikari: TRACE

springdoc:
  default-consumes-media-type: application/json;charset=UTF-8
  default-produces-media-type: application/json;charset=UTF-8
  swagger-ui:
    path: /swagger
    disable-swagger-default-url: true
    display-request-duration: true
    operations-sorter: alpha
  api-docs:
    groups:
      enabled: true

jwt:
  secret: exampleSecretKeyForSpringBootProjectAtSubRepository # TODO 운영 환경에서 수정
  token:
    # milliseconds 단위
    access-expiration-time: 1800000 # 30m (30 * 60 * 1000)
    refresh-expiration-time: 604800000 # 7d (7 * 24 * 60 * 60 * 1000)
    signup-access-expiration-time: 600000 # 10m (10 * 60 * 1000)
    signup-refresh-expiration-time: 600000 # 10m (10 * 60 * 1000)

ssh:
  host: ${SSH_HOST}
  user: ${SSH_USER}
  port: ${SSH_PORT}
  pem: ${SSH_PEM}
  database-port: ${SSH_DATABASE_PORT}

---
spring.config.activate.on-profile: develop

server:
  port: 8081
  forward-headers-strategy: FRAMEWORK
spring:
  jpa:
    database: MYSQL
    database-platform: org.hibernate.dialect.MySQL8Dialect
    open-in-view: false
    generate-ddl: false
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true
  datasource:
    hikari:
      driver-class-name: com.mysql.cj.jdbc.Driver
      jdbc-url: ${DB_URL}
      username: ${DB_USER_NAME}
      password: ${DB_PASSWORD}
      maximum-pool-size: 1 # (default 10)
      minimum-idle: 1 # (default 10)
      idle-timeout: 60000 # 1m (default 10m)
      max-lifetime: 1200000 # 20m (default 30m)
      connection-timeout: 3000 # 3s (default 30s)
      validation-timeout: 2000 # 2s (default 5s)
    url: ${DB_URL}
    username: ${DB_USER_NAME}
    password: ${DB_PASSWORD}
  data.redis:
    host: localhost
    port: 6379
  security: #OAuth2 연동 어플리케이션 정보 (TODO : 운영 어플리케이션 정보로 수정 필요)
    oauth2:
      client:
        registration:
          github:
            client-id: ${OAUTH2_GITHUB_CLIENT_ID}
            client-secret: ${OAUTH2_GITHUB_CLIENT_SECRET}

springdoc:
  default-consumes-media-type: application/json;charset=UTF-8
  default-produces-media-type: application/json;charset=UTF-8
  swagger-ui:
    path: /swagger
    disable-swagger-default-url: true
    display-request-duration: true
    operations-sorter: alpha
  api-docs:
    groups:
      enabled: true

jwt:
  secret: ${JWT_SECRET} # TODO 운영 환경에서 수정
  token:
    # milliseconds 단위
    access-expiration-time: 1800000 # 30m (30 * 60 * 1000)
    refresh-expiration-time: 604800000 # 7d (7 * 24 * 60 * 60 * 1000)
    signup-access-expiration-time: 600000 # 10m (10 * 60 * 1000)
    signup-refresh-expiration-time: 600000 # 10m (10 * 60 * 1000)
