ssh:
  host: ${SSH_HOST}
  user: ${SSH_USER}
  port: ${SSH_PORT}
  pem: ${SSH_PEM}
  database-port: ${SSH_DATABASE_PORT}
---
spring.config.activate.on-profile: local

server:
  port: 8081
spring:
  jpa:
    database: MYSQL
    database-platform: org.hibernate.dialect.MySQL8Dialect
    open-in-view: false
    generate-ddl: false
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true
  datasource:
    url: ${DB_URL}
    username: ${DB_USER_NAME}
    password: ${DB_PASSWORD}
    hikari:
      driver-class-name: com.mysql.cj.jdbc.Driver
      maximum-pool-size: 1 # (default 10)
      minimum-idle: 1 # (default 10)
      idle-timeout: 60000 # 1m (default 10m)
      max-lifetime: 1200000 # 20m (default 30m)
      connection-timeout: 3000 # 3s (default 30s)
    validation-timeout: 2000 # 2s (default 5s)
  security:
    #OAuth2 연동 어플리케이션 정보 (TODO : 운영 어플리케이션 정보로 수정 필요)
    oauth2:
      client:
        registration:
          github:
            client-id: Iv1.d984c2b9e76e6dc8
            client-secret: 057b0e172d21143af883b385a1a1e5434024977a
  cache:
    type: redis
    redis:
      time-to-live: 3600 # 데이터 유지 시간(sec)
      cache-null-values: true # null 캐싱 여부
      host: localhost
      port: 6379

springdoc:
  default-consumes-media-type: application/json;charset=UTF-8
  default-produces-media-type: application/json;charset=UTF-8
  swagger-ui:
    path: /swagger
    disable-swagger-default-url: true
    display-request-duration: true
    operations-sorter: alpha
  api-docs:
    groups:
      enabled: true
