name: Publish Docker Hub

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  docker:
    name: Deploy Docker Image
    runs-on: ubuntu-latest
    env:
      REPO: ${{ secrets.DOCKER_REPO }}
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'
      - name: set version from on push tags
        run: |
          TAG=${{ github.event.ref }}
          VERSION=${TAG#refs/tags/}
          echo "VERSION=${VERSION}" >> $GITHUB_ENV
      - name: create Github release
        uses: actions/create-release@v1
        with:
          tag_name: ${{ env.VERSION }}
          release_name: ${{ env.VERSION }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: build docker
        run: ./gradlew bootBuildImage --imageName=palco
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Publish Docker Image
        run: |
          docker push $REPO
          docker tag $REPO $REPO:${{ env.VERSION }}
          docker push $REPO:${{ env.VERSION }}